import React from 'react';
import { ExplanationResponse } from '../types/explanation';
import { Sparkles, CheckCircle2, AlertTriangle, ShieldCheck, Info } from 'lucide-react';

interface AIExplanationSectionProps {
  explanation: ExplanationResponse;
}

export const AIExplanationSection: React.FC<AIExplanationSectionProps> = ({ explanation }) => {
  const getEvidenceIcon = (evidenceText: string) => {
    if (evidenceText.startsWith('[STRONG_CORRELATION]')) return <ShieldCheck className="text-success" size={16} />;
    if (evidenceText.startsWith('[WEAK_CORRELATION]')) return <AlertTriangle className="text-warning" size={16} />;
    if (evidenceText.startsWith('[DIRECT_EVIDENCE]')) return <CheckCircle2 className="text-primary" size={16} />;
    return <Info className="text-secondary" size={16} />;
  };

  const parseEvidenceText = (text: string) => {
    const match = text.match(/^\[(.*?)\]\s*(.*)$/);
    if (match) {
      return (
        <span>
          <strong>{match[1].replace('_', ' ')}:</strong> {match[2]}
        </span>
      );
    }
    return <span>{text}</span>;
  };

  return (
    <div className="card explanation-card">
      <div className="explanation-header">
        <div className="flex items-center gap-2">
          <Sparkles className="icon-sparkles" size={24} />
          <h2>AI Root-Cause Explanation</h2>
        </div>
        <div className="flex items-center gap-4">
          <span className="text-sm text-secondary">
            Confidence: <strong className="text-primary">{(explanation.confidence * 100).toFixed(0)}%</strong>
          </span>
          <div className="badge-ai">Generated by AI</div>
        </div>
      </div>
      
      <div className="explanation-section mt-4">
        <h3 className="text-lg font-semibold mb-2">What Happened</h3>
        <div className="explanation-summary p-4 bg-background-light rounded-md border border-border">
          {explanation.what_happened}
        </div>
      </div>

      <div className="explanation-section mt-4">
        <h3 className="text-lg font-semibold mb-2">Why It Likely Happened</h3>
        <div className="p-4 bg-background-light rounded-md border border-border">
          {explanation.why_it_happened}
        </div>
      </div>

      <div className="explanation-section mt-4">
        <h3 className="text-lg font-semibold mb-2">Key Evidence</h3>
        <ul className="evidence-list space-y-2">
          {explanation.key_evidence.map((evidence, idx) => (
            <li key={idx} className="flex items-start gap-2 p-3 bg-background-light rounded-md border border-border text-sm">
              <div className="mt-0.5">{getEvidenceIcon(evidence)}</div>
              <div>{parseEvidenceText(evidence)}</div>
            </li>
          ))}
        </ul>
      </div>

      <div className="remediation-section mt-6 p-4 bg-primary-light rounded-md border border-primary-glow">
        <h3 className="flex items-center gap-2 text-primary font-semibold mb-2">
          <CheckCircle2 size={18} /> Recommended Next Step
        </h3>
        <p className="text-sm">{explanation.recommended_next_step}</p>
      </div>
    </div>
  );
};
