import React from 'react';
import { AIExplanation } from '../types/root_cause';
import { Sparkles, CheckCircle2, ChevronRight } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface AIExplanationSectionProps {
  explanation: AIExplanation;
}

export const AIExplanationSection: React.FC<AIExplanationSectionProps> = ({ explanation }) => {
  return (
    <div className="card explanation-card">
      <div className="explanation-header">
        <Sparkles className="icon-sparkles" size={24} />
        <h2>AI Root-Cause Analysis</h2>
        <div className="badge-ai">Generated by AI</div>
      </div>
      
      <div className="explanation-summary">
        {explanation.summary}
      </div>

      <div className="explanation-narrative">
        <ReactMarkdown>{explanation.narrative}</ReactMarkdown>
      </div>

      {explanation.remediation_steps.length > 0 && (
        <div className="remediation-section">
          <h3><CheckCircle2 size={18} /> Recommended Remediation</h3>
          <ul className="remediation-list">
            {explanation.remediation_steps.map((step, idx) => (
              <li key={idx}>
                <ChevronRight size={16} className="text-secondary" />
                <span>{step}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};
