import React, { useState, useEffect } from 'react';
import { FileText, Download, Loader2, FileCheck, Trash2 } from 'lucide-react';
import { AnomalyItem } from '../types/anomaly';
import { fetchExecutiveSummary } from '../services/api';
import { ExecutiveSummaryResponse } from '../types/executive_summary';

interface ReportsPageProps {
  anomalies: AnomalyItem[];
}

interface GeneratedReport {
  id: string;
  anomalyId: string;
  service: string;
  timestamp: number;
  content: string;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ anomalies }) => {
  const [selectedAnomalyId, setSelectedAnomalyId] = useState<string>('');
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reports, setReports] = useState<GeneratedReport[]>([]);

  // Load history from localStorage
  useEffect(() => {
    try {
      const history = localStorage.getItem('spendtrace_reports');
      if (history) {
        setReports(JSON.parse(history));
      }
    } catch (e) {
      console.error('Failed to parse reports history', e);
    }
  }, []);

  // Update selected anomaly if it's empty and we have anomalies
  useEffect(() => {
    if (!selectedAnomalyId && anomalies.length > 0) {
      setSelectedAnomalyId(anomalies[0].anomaly_id);
    }
  }, [anomalies, selectedAnomalyId]);

  const saveReports = (newReports: GeneratedReport[]) => {
    setReports(newReports);
    try {
      localStorage.setItem('spendtrace_reports', JSON.stringify(newReports));
    } catch (e) {
      console.error('Failed to save reports to localStorage', e);
    }
  };

  const generateMarkdown = (summary: ExecutiveSummaryResponse): string => {
    const { anomaly, top_root_causes, explanation, financial_impact, graph } = summary;
    
    if (!anomaly) return '# Error: Anomaly data missing';

    const date = new Date().toISOString().split('T')[0];
    
    let md = `# SpendTrace Investigation Report: ${anomaly.service}\n\n`;
    md += `**Date Generated:** ${date}\n`;
    md += `**Anomaly ID:** \`${anomaly.anomaly_id}\`\n`;
    md += `**Severity:** ${anomaly.severity}\n\n`;

    md += `## 1. Anomaly Overview\n`;
    md += `- **Service:** ${anomaly.service}\n`;
    md += `- **Region:** ${anomaly.region}\n`;
    md += `- **Team:** ${anomaly.team}\n`;
    md += `- **Resource ID:** \`${anomaly.resource_id}\`\n\n`;

    if (financial_impact) {
      md += `## 2. Financial Impact\n`;
      md += `| Metric | Value |\n|---|---|\n`;
      md += `| Expected Daily Cost | $${financial_impact.expected_cost.toFixed(2)} |\n`;
      md += `| Actual Daily Cost | $${financial_impact.current_anomalous_cost.toFixed(2)} |\n`;
      md += `| Daily Excess | $${financial_impact.excess_cost.toFixed(2)} |\n`;
      md += `| 30-Day Projected Excess | **$${financial_impact.projected_30_day_excess.toFixed(2)}** |\n`;
      md += `| Potential 30-Day Savings | **$${financial_impact.potential_savings.toFixed(2)}** |\n\n`;
    }

    if (explanation) {
      md += `## 3. AI Root-Cause Explanation\n`;
      md += `**What Happened:** ${explanation.what_happened}\n\n`;
      md += `**Why It Happened:** ${explanation.why_it_happened}\n\n`;
      if (explanation.recommended_next_step) {
        md += `**Recommended Action:** ${explanation.recommended_next_step}\n\n`;
      }
      if (explanation.confidence !== undefined) {
        md += `*AI Confidence Score: ${(explanation.confidence * 100).toFixed(0)}%*\n\n`;
      }
    }

    if (top_root_causes && top_root_causes.length > 0) {
      md += `## 4. Top Root Cause Candidates\n`;
      top_root_causes.forEach((cause, idx) => {
        md += `### ${idx + 1}. ${cause.title} (${cause.category})\n`;
        md += `- **Description:** ${cause.description}\n`;
        md += `- **Confidence:** ${(cause.confidence * 100).toFixed(1)}%\n`;
        if (cause.evidence && cause.evidence.length > 0) {
          md += `- **Evidence:**\n`;
          cause.evidence.forEach(ev => {
            md += `  - ${ev}\n`;
          });
        }
        md += `\n`;
      });
    }

    if (graph && graph.nodes && graph.edges) {
      md += `## 5. Investigation Graph Summary\n`;
      md += `**Nodes Involved:** ${graph.nodes.length}\n`;
      md += `**Relationships Found:** ${graph.edges.length}\n\n`;
      
      md += `### Key Relationships:\n`;
      graph.edges.forEach(edge => {
        const source = graph.nodes.find(n => n.id === edge.source);
        const target = graph.nodes.find(n => n.id === edge.target);
        if (source && target) {
          md += `- **${source.type}** (${source.label}) *[${edge.relationship}]* **${target.type}** (${target.label})\n`;
        }
      });
      md += `\n`;
    }

    md += `---\n*Generated by SpendTrace AI*\n`;
    return md;
  };

  const handleGenerate = async () => {
    if (!selectedAnomalyId) return;
    
    setGenerating(true);
    setError(null);
    try {
      const summary = await fetchExecutiveSummary(selectedAnomalyId);
      const markdown = generateMarkdown(summary);
      
      const newReport: GeneratedReport = {
        id: crypto.randomUUID(),
        anomalyId: selectedAnomalyId,
        service: summary.anomaly?.service || 'Unknown Service',
        timestamp: Date.now(),
        content: markdown
      };
      
      saveReports([newReport, ...reports]);
    } catch (err: any) {
      setError(err.message || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const downloadMarkdown = (report: GeneratedReport) => {
    const blob = new Blob([report.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SpendTrace_Report_${report.service}_${new Date(report.timestamp).toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const deleteReport = (id: string) => {
    saveReports(reports.filter(r => r.id !== id));
  };

  return (
    <div className="flex-col gap-6 w-full max-w-4xl mx-auto">
      
      <div className="glass-card p-6">
        <div className="flex items-center gap-3 mb-6">
          <FileText className="text-primary" size={24} />
          <h2 className="text-xl font-bold">Investigation Reports</h2>
        </div>
        
        <p className="text-secondary mb-6">
          Compile all data for a specific anomaly (including financial impact, AI explanations, and evidence graphs) into a single downloadable Markdown report.
        </p>

        <div className="flex flex-col md:flex-row gap-4 items-end bg-surface p-4 rounded-md border border-subtle">
          <div className="flex-1 w-full">
            <label className="block text-sm font-semibold text-secondary mb-2">Select Anomaly Incident</label>
            <select
              value={selectedAnomalyId}
              onChange={(e) => setSelectedAnomalyId(e.target.value)}
              className="w-full bg-card border border-subtle text-primary p-2.5 rounded text-sm outline-none focus:border-primary transition-colors"
              disabled={generating || anomalies.length === 0}
            >
              {anomalies.length === 0 && <option value="">No anomalies available</option>}
              {anomalies.map((a) => (
                <option key={a.anomaly_id} value={a.anomaly_id}>
                  {a.service} (+${a.absolute_delta.toLocaleString()}) - {a.region}
                </option>
              ))}
            </select>
          </div>
          <button
            onClick={handleGenerate}
            disabled={generating || !selectedAnomalyId}
            className="bg-primary hover:bg-primary-hover text-white px-6 py-2.5 rounded font-medium flex items-center justify-center min-w-[160px] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generating ? (
              <>
                <Loader2 size={18} className="animate-spin mr-2" />
                Compiling...
              </>
            ) : (
              <>
                <FileCheck size={18} className="mr-2" />
                Generate Report
              </>
            )}
          </button>
        </div>
        
        {error && (
          <div className="mt-4 p-3 bg-critical/10 border border-critical/30 rounded text-critical text-sm flex items-center gap-2">
            <strong>Error:</strong> {error}
          </div>
        )}
      </div>

      <div className="glass-card p-6 mt-6">
        <h3 className="font-bold text-lg mb-4">Generated Reports History</h3>
        
        {reports.length === 0 ? (
          <div className="text-center p-8 bg-surface border border-subtle rounded-md text-secondary">
            No reports generated yet. Select an anomaly above to create one.
          </div>
        ) : (
          <div className="space-y-3">
            {reports.map(report => (
              <div key={report.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 bg-surface border border-subtle rounded-md hover:border-white/20 transition-colors gap-4">
                <div>
                  <div className="font-bold text-primary mb-1">
                    {report.service} Investigation Report
                  </div>
                  <div className="text-xs text-secondary flex items-center gap-3">
                    <span>{new Date(report.timestamp).toLocaleString()}</span>
                    <span>•</span>
                    <span className="font-mono text-white/40">{report.anomalyId}</span>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <button 
                    onClick={() => downloadMarkdown(report)}
                    className="flex items-center gap-1.5 text-sm bg-card hover:bg-white/10 px-3 py-1.5 rounded border border-subtle transition-colors text-white"
                  >
                    <Download size={14} />
                    Download (.md)
                  </button>
                  <button
                    onClick={() => deleteReport(report.id)}
                    className="p-1.5 text-secondary hover:text-critical hover:bg-critical/10 rounded transition-colors"
                    title="Delete report"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
};
